services:
  postgres:
    image: postgres:17-alpine
    container_name: anomie-postgres
    environment:
      POSTGRES_DB: anomie
      POSTGRES_USER: anomie
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
